keetest/accounts/urls.py
from django.urls import path
from .forms import LoginForm

from . import views

from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user=True, authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html', next_page='accounts:login'), name='logout'),
    path('register/', views.register, name='register'),
]

keetest/keetest/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

keetest/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:id>/', views.details, name='details'),
    path('new_post/', views.new_post, name='new_post'),
    path('update_post/<int:id>/', views.update_post, name='update_post'),
    path('delete_post/<int:id>/', views.delete_post, name='delete_post'),
    path('search_posts/', views.search_posts, name='search_posts'),
]

keetest/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from PIL import Image
# Create your models here.

phoneNumberRegex = RegexValidator(regex = r"^\+?1?\d{8,15}$")

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    birthday = models.DateField()
    phonenumber = models.CharField(validators = [phoneNumberRegex], max_length = 16, unique = True)
    image = models.ImageField(upload_to='accounts_images/', null=True, blank=True)


    def __str__(self):
        return self.user.username

    #def save(self, *args, **kwargs):
    #    super().save(*args, **kwargs)

    #img = Image.open(self.image.path)
    #if img.height > 300 or img.width > 300:
    #    output_size = (300, 300)
    #    img.thumbnail(output_size)
    #    img.save(self.image.path)
    

keetest/posts/models.py
from turtle import title
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=55)
    content = models.TextField()
    image = models.ImageField(upload_to='posts_images/', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=True)

    def __str__(self):
        return f'title:{self.title} \ content:{self.content}\ns'

keetest/accounts/forms.py
from dataclasses import fields
from django import forms
from .models import Profile

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from django.contrib.auth.models import User

#login form
class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))

#register Form
class UserForm(UserCreationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    first_name = forms.CharField(label='First Name', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    last_name = forms.CharField(label='Last Name', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))

    email = forms.CharField(label='Email Address', widget=forms.EmailInput(attrs={
        'class': 'form-control',
    }))

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))

    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class ProfileForm(forms.ModelForm):
    birthday = forms.DateField(label='Birthday', widget=forms.DateInput(attrs={
        'class': 'form-control',
        'type': 'date',
    }))
    phonenumber = forms.CharField(label='Phone Number', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    
    class Meta:
        model = Profile
        fields = ('birthday', 'phonenumber', 'image')

keetest/posts/forms.py
from dataclasses import field

from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    content = forms.CharField(label='Content', widget=forms.Textarea(attrs={
        'class': 'form-control',
    }))

    class Meta:
        model = Post
        fields = ('title', 'content', 'image')

keetest/accounts/views.py
from ast import If
from multiprocessing import context
from django.shortcuts import render, redirect

from .forms import UserForm, ProfileForm

# Create your views here.

def register(request):
    if request.user.is_authenticated:
        return redirect('posts:index')

    if request.method == "POST":
        form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if form.is_valid() and profile_form.is_valid():
            user = form.save(commit= False)
            
            profile = profile_form.save(commit=False)
            profile.user = user

            user.save()
            profile.save()
            
            return redirect('accounts:login')

    else:
        form = UserForm()
        profile_form = ProfileForm()

    context = {
        'form': form,
        'profile': profile_form,
    }
    return render(request, 'accounts/register.html', context)

keetest/posts/views.py
from multiprocessing import context
from turtle import title
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator


# Create your views here.

@login_required
def index(request):
    posts = Post.objects.order_by('-id').all()
    paginator = Paginator(posts, 3)

    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    posts_count = posts.count()

    if posts_count ==1 :
        message = '1 Post :'
    else:
        message = f'{posts_count} Posts :'

    context = {
        "posts" : page_object,
        'message': message,
    }

    return render(request, 'posts/index.html', context)

@login_required
def details(request, id):
    post = Post.objects.get(id=id)

    context ={
        'post': post,
    }
    return render(request, 'posts/details.html', context)

@login_required
def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()  
            return redirect('posts:index')  
    else:
        form = PostForm()
    

    context ={
        'form': form,
    }

    return render(request, 'posts/new_post.html', context)

def update_post(request, id):
    post = Post.objects.get(id=id)

    if post.user ==request.user:
        if request.method == 'POST':
            form = PostForm(request.POST, request.FILES, instance=post)
            if form.is_valid:
                form.save()
                return redirect('posts:index')
        else:
            form = PostForm(instance=post)
    else:
        raise Http404

    context ={
        'form': form,
        'post': post,
    }

    return render(request, 'posts/update_post.html', context)

def delete_post(request, id):
    post = Post.objects.get(id=id)

    if post.user == request.user:
        post.delete()
        return redirect('posts:index')
    else:
        raise Http404
    return render(request, 'posts/delete_post.html')

@login_required
def search_posts(request):
    search = request.GET['search']

    posts = Post.objects.filter(Q(title__icontains=search) |
                                Q(content__icontains=search) |
                                Q(image__icontains=search))
    posts_count = posts.count()

    if posts_count ==1 :
        message = '1 Post find :'
    else:
        message = f'{posts_count} Posts find :'

    context ={
        'posts': posts,
        'message': message,
    }
    return render(request, 'posts/search_posts.html', context)

keetest/accounts/templates/accounts/layouts/base.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
{% endblock stylesheets %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'accounts/js/app.js' %}"></script>
{% endblock javascript %}

keetest/accounts/templates/accounts/login.html
{% extends 'accounts/layouts/base.html' %}

{% block title %}Login{% endblock title %}

{% block body %}
<div class='container-fluid'>
    <div class='row'>
        <div class='col-md-8 mx-auto'>
            <h3 class='text-center mb-3'>Login</h3>
            <form action="" method="post" enctype='multipart/form-data'>
                {% if form.non_field_errors %}
                    {% for error in form.non_field.errors %}
                        <p class='text-danger'><strong>{{ error }}</strong></p>
                    {% endfor %}
                {% endif %}
                {% csrf_token %}
                {% for field in form  %}
                    <div class="form-group mb-3">
                        <strong>{{ field.label_tag }}</strong>{% if field.field.required %}
                            <span class=required>*</span>
                        {% endif %}
                        {{ field }}
                        {% if field.help_text %}
                            <small class='help'>{{ field.help_text }}</small>
                        {% endif %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <p class='text-danger'><strong>{{ error }}</strong></p>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}
                <input name="" id="" class="btn btn-primary mb-2" type="submit" value="Login">
            </form>
        </div>
    </div>
    <div class='col-md-4'></div>
</div>
{% endblock body %}

keetest/accounts/templates/accounts/register.html
{% extends 'accounts/layouts/base.html' %}

{% block title %}Signup{% endblock title %}

{% block body %}
<div class='container-fluid'>
    <div class='row'>
        <div class='col-md-8 mx-auto'>
            <h3 class='text-center mb-3'>Sign Up</h3>
            <form action="" method="post" enctype='multipart/form-data'>
                {% if form.non_field_errors %}
                    {% for error in form.non_field.errors %}
                        <p class='text-danger'><strong>{{ error }}</strong></p>
                    {% endfor %}
                {% endif %}
                {% csrf_token %}
                {% for field in form  %}
                    <div class="form-group mb-3">
                        <strong>{{ field.label_tag }}</strong>{% if field.field.required %}
                            <span class=required>*</span>
                        {% endif %}
                        {{ field }}
                        {% if field.help_text %}
                            <small class='help'>{{ field.help_text }}</small>
                        {% endif %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <p class='text-danger'><strong>{{ error }}</strong></p>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}
                {% if profile.non_field_errors %}
                    {% for error in profile.non_field.errors %}
                        <p class='text-danger'><strong>{{ error }}</strong></p>
                    {% endfor %}
                {% endif %}
    
                {% for field in profile  %}
                    <div class="form-group mb-3">
                        <strong>{{ field.label_tag }}</strong>{% if field.field.required %}
                            <span class=required>*</span>
                        {% endif %}
                        {{ field }}
                        {% if field.help_text %}
                            <small class='help'>{{ field.help_text }}</small>
                        {% endif %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <p class='text-danger'><strong>{{ error }}</strong></p>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}
                <input name="" id="" class="btn btn-primary mb-2" type="submit" value="Sign Up">
            </form>
        </div>
    </div>
    <div class='col-md-4'></div>
</div>
{% endblock body %}

keetest/posts/templates/posts/details.html
{% extends 'posts/layouts/base.html' %}

{% block title %}
	Details
{% endblock title %}

{% block body %}

	<h1>Details</h1>
	<div class="card">
		{% if post.image %}
			<img src="{{ post.image.url }}" class='card-img-top' alt='HELLO'> 
		{% endif %}
		<div class="card-header">  
			{{ post.title }} 
		</div>
		<div class="card-body">
			<p class="card-text">{{post.content}}</p>
		</div>
		<div class='card-footer'>
			{% if post.user ==request.user %}
				<a href="{% url 'posts:update_post' post.id %}" class="btn btn-info">Update</a>
				<a href="{% url 'posts:delete_post' post.id %}" class="btn btn-danger">Delete</a>
			{% endif %}
			
		</div>
	</div>

{% endblock body %}

keetest/posts/templates/posts/index.html
{% extends 'posts/layouts/base.html' %}

{% block title %}
	Home
{% endblock title %}

{% block body %}

	<h1>KEECASH</h1>
	<div>
		<h3 class="text-center mb-4 shadow bg-info">  {{ message }} </h3>

		<div class="row row-cols-md-3 row-cols-sm-2">
			{% for post in posts %}
				<div class="col-sm-6">
					<div class="custom-card card mb-3 shadow" style='width: 18rem;'>
						{% if post.image %}
							<img src="{{ post.image.url }}" class='card-img-top' alt='HELLO' style='height: 15rem;'> 
						{% endif %}
						
						<div class="card-body">
							<h5 class="card-title"> {{ post.title }} </h5>
							<p class="card-text">{{ post.content|truncatechars:"50" }}</p>
							<a href="{% url 'posts:details' post.id %}" class="btn btn-primary">More</a>
							{% if post.user == request.user %}
								<a href="{% url 'posts:update_post' post.id %}" class="btn btn-info">Update</a>
								<a href="{% url 'posts:delete_post' post.id %}" class="btn btn-danger">Delete</a>
							{% endif %}
							
						</div>
						<div class='card-footer'>
							Created by @{{ post.user.username }}
						</div>
					</div>
				</div>
			{% endfor%}
		</div>
	</div>

	<nav>
		<ul class='pagination justify-content-center'>
			{% if posts.has_previous %}
				<li class='page_item'>
					<a class="page-link" href="?page={{ posts.previous_page_number }}">
						<span aria-hidden="true">&laquo;</span>
					</a>
				</li>
			{% endif %}
			<li class="page-item">
				<p class="page-link text-muted">
					{{ posts.number }} of {{ posts.paginator.num_pages }}.
				</p>
			</li>
			{% if posts.has_next %}
				<li class='page_item'>
					<a class="page-link" href="?page={{ posts.next_page_number }}">
						<span aria-hidden="true">&raquo;</span>
					</a>
				</li>
			{% endif %}
			
		</ul>
	</nav>

{% endblock body %}

keetest/posts/templates/posts/layouts/base.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'posts/css/style.css' %}">
{% endblock stylesheets %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'posts/js/app.js' %}"></script>
{% endblock javascript %}

keetest/posts/templates/posts/new_post.html
{% extends 'posts/layouts/base.html' %}

{% block title %}New Posts{% endblock title %}

{% block body %}

    <h3 class='text-center mb-4'>New Post</h3>
    <div class='container-fluid'>
        <div class='row'>
            <div class='col-md-8 mx-auto'>
                <form action="" method="post" enctype='multipart/form-data'>
                    {% if form.subject.errors %}
                        {% for error in form.subject.errors %}
                            <p class='text-danger'><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in form  %}
                        <div class="form-group mb-2">
                            <strong>{{ field.label_tag }}</strong>{% if field.field.required %}
                                <span class=required>*</span>
                            {% endif %}
                            {{ field }}
                            {% if field.help_text %}
                                <small class='help'>{{ field.help_text }}</small>
                            {% endif %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class='text-danger'><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    <input name="" id="" class="btn btn-primary mb-2" type="submit" value="New Post">
                </form>
            </div>
        </div>
        <div class='col-md-4'></div>
    </div>
    
{% endblock body %}

keetest/posts/templates/posts/search_posts.html
{% extends 'posts/layouts/base.html' %}

{% block title %}
	Posts find
{% endblock title %}

{% block body %}

	<h3 class='text-center'>{{ message }}</h3>
    <div class="row row-cols-md-3 row-cols-sm-2">
        {% for post in posts %}
            <div class="col-sm-6">
                <div class="custom-card card mb-3 shadow" style='width: 18rem;'>
                    {% if post.image %}
                        <img src="{{ post.image.url }}" class='card-img-top' alt='HELLO' style='height: 15rem;'> 
                    {% endif %}
                    
                    <div class="card-body">
                        <h5 class="card-title"> {{ post.title }} </h5>
                        <p class="card-text">{{ post.content|truncatechars:"50" }}</p>
                        <a href="{% url 'posts:details' post.id %}" class="btn btn-primary">More</a>
                        {% if post.user == request.user %}
                            <a href="{% url 'posts:update_post' post.id %}" class="btn btn-info">Update</a>
                            <a href="{% url 'posts:delete_post' post.id %}" class="btn btn-danger">Delete</a>
                        {% endif %}
                        
                    </div>
                    <div class='card-footer'>
                        Created by @{{ post.user.username }}
                    </div>
                </div>
            </div>
        {% endfor%}
    </div>

{% endblock body %}

keetest/posts/templates/posts/update_post.html
{% extends 'posts/layouts/base.html' %}

{% block title %}Update post{% endblock title %}

{% block body %}
    <h3 class='text-center'>Update page</h3>
    <div class='container-fluid'>
        <div class='row'>
            <div class='col-md-8 mx-auto'>
                <form action="" method="post" enctype='multipart/form-data'>
                    {% if form.subject.errors %}
                        {% for error in form.subject.errors %}
                            <p class='text-danger'><strong>{{ error }}</strong></p>
                        {% endfor %}
                    {% endif %}
                    {% csrf_token %}
                    {% for field in form  %}
                        <div class="form-group mb-2">
                            <strong>{{ field.label_tag }}</strong>{% if field.field.required %}
                                <span class=required>*</span>
                            {% endif %}
                            {{ field }}
                            {% if field.help_text %}
                                <small class='help'>{{ field.help_text }}</small>
                            {% endif %}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class='text-danger'><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                            {% if field.name == 'image' %}
                                <img src="{{ post.image.url }}" class='card-img-bottom mb-3' >
                            {% endif %}
                            
                        </div>
                    {% endfor %}
                    <input name="" id="" class="btn btn-info mb-2" type="submit" value="Update">
                </form>
            </div>
        </div>
        <div class='col-md-4'></div>
    </div>
{% endblock body %}

keetest/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock title %} | Keetest</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

	{% block stylesheets %}{% endblock stylesheets %}

	
	<!--script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script-->
</head>

<body>
	<header>
		{% include 'layouts/partials/header.html' %}
	</header>

	<div class='body container'>
		{% block body %}
			<h1>KEECASH</h1>
		{% endblock body %}
	</div>

	<app-footer class="footer p-3 mt-5">
		{% include 'layouts/partials/footer.html' %}
	</app-footer>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
	
	{% block javascript %}{% endblock javascript %}

</body>	

</html>

keetest/templates/layouts/partials/footer.html
<footer _ngcontent-c2 class="py-1 bg-light text-dark">
	<div _ngcontent-c2 class="text-center">
		<small _ngcontent-c2="">Copyright © KeeCash © {% now "Y" %} </small>
	</div>
</footer>

keetest/templates/layouts/partials/header.html
<div class="m-4">
    <nav class="navbar navbar-expand-lg navbar-dark mb-10 shadow-lg">
        <div class="container-fluid">
            <a href="{% url 'posts:index' %}" class="navbar-brand">
                {% load static %}
                <img src="{% static 'img/logo.jpg' %}" height="32" alt="KEECASHFUND">
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav ms-auto">

                    {% if request.user.is_authenticated %}
                        
                        <a href="#" class="nav-item nav-link text-white">Dashboard</a>
                        <a href="https://aide.keecash.com" class="nav-item nav-link text-white">FAQ</a>
                        <a href="{% url 'posts:new_post' %}" class="nav-item nav-link text-white" tabindex="-1">New Post</a>
                        <a href="{% url 'accounts:logout' %}" class="nav-item nav-link text-white">Log Out</a>
                        <a href='#' class='nav-item nav-link text-dark'>Hi {{ request.user.username }}</a>
                        
						<img src="{{ request.user.profile.image.url }}" class='rounded-circle article-img' alt='img' style="height: 2rem; width: 2rem;"> 
                        

                    {% else %}
                    
                        <a href="{% url 'accounts:login' %}" class="nav-item nav-link text-white" tabindex="-1">Login</a>
                        <a href="{% url 'accounts:register' %}" class="nav-item nav-link text-white">Sign Up</a>    

                    {% endif %}
                    
                </div>
            </div>

            <form action= "{% url 'posts:search_posts' %}" method="get" class='d-flex ml-3'>
                <input placeholder='Search a post here' class="form-control me-2" type='search' name='search'>
                <button class='btn btn-outline-success ml-2' type='submit'>Search</button>
            </form>

        </div>
    </nav>
</div>

keetest/templates/pages/index.html
{% extends 'layouts/base.html' %}

{% block title %}
	Home
{% endblock title %}

{% block body %}

	<h1>KEECASH</h1>

{% endblock body %}